reporting

diff --git a/.github/workflows/cherry-pick-openedx.yml b/.github/workflows/cherry-pick-openedx.yml
--- a/.github/workflows/cherry-pick-openedx.yml
+++ b/.github/workflows/cherry-pick-openedx.yml
@@ -40,7 +40,11 @@ jobs:
           set -e
           BRANCH_NAME="${{ github.actor }}/cherry-pick-${{ steps.commit-info.outputs.hash }}"
           git checkout -b $BRANCH_NAME
-          git cherry-pick ${{ inputs.targetCommitHash }}
+          git cherry-pick ${{ inputs.targetCommitHash }} &> cherry_pick_errors
+          if [[ $? != 0]]; then
+            echo "## Unable to cherry-pick commit" >> $GITHUB_STEP_SUMMARY
+            cat cherry_pick_errors >> $GITHUB_STEP_SUMMARY
+
           git push -u edx $BRANCH_NAME
 
       - name: Open pull request
@@ -54,4 +58,11 @@ jobs:
             Date: ${{ steps.commit-info.outputs.date }}
           EOF
           )
-          gh pr create --title "${{ steps.commit-info.outputs.commit_subject }}" --body "$BODY" 
+          gh pr create --title "${{ steps.commit-info.outputs.commit_subject }}" --body "$BODY" &> pr_creation_output
+          if [[ $? != 0 ]]; then
+              echo "## Pull Request Created! 🎉" >> $GITHUB_STEP_SUMMARY;
+          else;
+              echo "## Pull request creation failed" >> $GITHUB_STEP_SUMMARY;
+          fi;
+          
+          echo $(cat pr_creation_output) >> $GITHUB_STEP_SUMMARY;
