fixup! fixup! fixup! reporting

diff --git a/.github/workflows/cherry-pick-openedx.yml b/.github/workflows/cherry-pick-openedx.yml
--- a/.github/workflows/cherry-pick-openedx.yml
+++ b/.github/workflows/cherry-pick-openedx.yml
@@ -44,7 +44,7 @@ jobs:
             echo "## Unable to cherry-pick commit" >> $GITHUB_STEP_SUMMARY
             cat cherry_pick_errors >> $GITHUB_STEP_SUMMARY
             exit 1
-          fi;
+          fi
 
           git push -u edx $BRANCH_NAME
 
@@ -60,10 +60,12 @@ jobs:
           EOF
           )
           gh pr create --title "${{ steps.commit-info.outputs.commit_subject }}" --body "$BODY" &> pr_creation_output
-          if [[ $? != 0 ]]; then
-              echo "## Pull Request Created! 🎉" >> $GITHUB_STEP_SUMMARY;
-          else;
-              echo "## Pull request creation failed" >> $GITHUB_STEP_SUMMARY;
-          fi;
+          STATUS=$?
+          if [[ STATUS != 0 ]]; then
+              echo "## Pull Request Created! 🎉" >> $GITHUB_STEP_SUMMARY
+          else
+              echo "## Pull request creation failed" >> $GITHUB_STEP_SUMMARY
+          fi
           
-          echo $(cat pr_creation_output) >> $GITHUB_STEP_SUMMARY;
+          echo $(cat pr_creation_output) >> $GITHUB_STEP_SUMMARY
+          exit $STATUS
